project:
  type: website
  output-dir: docs

website:
  title: "maybout.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: 30DayChartChallenge.qmd
        text: 30DayChartChallenge

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



